### ISSUE TITLE
OSC Client: Add Ardour DAW support

### ISSUE THREAD

**Issue by oubiwann** [lfex/undertone#7]
Tasks:

* [x] Create a psuedo-package for Ardour OSC support
* [x] Re-examine code re-use for all OSC clients and improve as applicable
* [x] Examine the [Ardour OSC docs](https://manual.ardour.org/using-control-surfaces/controlling-ardour-with-osc/osc-control/) for a good set of initial OSC addresses to support
* [x] Implement select addresses:
   * [x] `/strip/list`
   * [x] `/strip/plugin/list ssid`
   * [x] `/strip/plugin/descriptor ssid`
   * [x] `/strip/select ssid y/n`
   * [x] `/goto_start`
   * [x] `/monitor/mute`

Branch:

* [epic/7/ardour-osc](https://github.com/lfex/undertone/tree/epic/7/ardour-osc)

Resources:

* https://manual.ardour.org/using-control-surfaces/controlling-ardour-with-osc/osc-control/
