### ISSUE TITLE
Provide LFE-native versions of core Extempore feartures

### ISSUE THREAD

**Issue by oubiwann** [lfex/undertone#82]
Any backends that lack some of Extempore's features will need an approximation of those offered by undertone, written in LFE.

Thoughts:

* [ ] Add timing server (with metronome API)
* [ ] Add utilities for converting between time intervals and beats
* [ ] Add `apply-after` for beats (analog to `timer:apply_after` for milliseconds)
* [ ] Add support for modes / degrees (e.g., I, ii, V, vi, etc.) with all the convenience functions for generating chords, etc.

**Comment by oubiwann** [comment]
I had thought this would be needed for the new "Bevin" backend (see #80), but simply sending time stamps or relative intervals does that for those tools.
