### ISSUE TITLE
Extempore updates for 0.4.0

### ISSUE THREAD

**Issue by oubiwann** [lfex/undertone#92]
Tasks:

* [x] Download the latest Extempore (0.8.8)
* [x] #90 - Have `xt` use the new banner-display functions
* [x] #91 - Update the `xt` backend to use the new `exec` dependency for proper shutdown of the `extempore` OS process
* [x] Fix up logging (now that raw stdout is being used, instead of line-parsing)
* [x] #93 - Utilise the new/correct logic for post-banner prompt display

**Comment by oubiwann** [comment]
Done.
